name: hello workd

on:
  push:
    branches:[main,develop,other]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Hello World MEssage
        run : echo "Hello"

      - name: Another Task
        run:  echo "Another task"
          
